 "use client";
import {useMemo,useState} from "react";
import {useRouter} from "next/navigation";

type Med=any;
export default function POSClient({medicines}:{medicines:Med[]}){
 const [q,setQ]=useState("");const [cart,setCart]=useState<any[]>([]);const [paid,setPaid]=useState("");const [method,setMethod]=useState("CASH");const [msg,setMsg]=useState("");const router=useRouter();
 const results=useMemo(()=>medicines.filter(m=>`${m.name} ${m.genericName||""} ${m.barcode||""} ${m.productId}`.toLowerCase().includes(q.toLowerCase())).slice(0,8),[q,medicines]);
 const total=cart.reduce((s,i)=>s+i.quantity*i.unitPrice,0);const change=Math.max(0,Number(paid||0)-total);
 function add(m:Med){const b=m.batches[0];if(!b)return;setCart(c=>{const old=c.find(x=>x.medicineId===m.id&&x.batchId===b.id);if(old)return c.map(x=>x===old?{...x,quantity:x.quantity+1}:x);return [...c,{medicineId:m.id,batchId:b.id,name:m.name,batch:b.batchNumber,expiry:b.expiryDate,quantity:1,unitPrice:b.salePrice,costPrice:b.purchasePrice}]});setQ("");}
 function update(i:number,qty:number){setCart(c=>c.map((x,n)=>n===i?{...x,quantity:Math.max(1,qty)}:x))}
 async function complete(){setMsg("");if(!cart.length){setMsg("Cart is empty");return;}if(Number(paid)<total&&method!=="CREDIT"){setMsg("Paid amount is less than total");return;}const r=await fetch("/api/sales",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:cart.map(x=>({medicineId:x.medicineId,batchId:x.batchId,quantity:x.quantity,unitPrice:x.unitPrice,costPrice:x.costPrice})),paid:Number(paid||0),paymentMethod:method})});const j=await r.json();if(!r.ok){setMsg(j.error||"Sale failed");return;}setCart([]);setPaid("");setMsg(`Sale ${j.invoiceNumber} completed`);router.refresh();}
 return <div className="grid xl:grid-cols-[1fr_420px] gap-5">
 <div className="space-y-4"><div><h1 className="text-2xl font-black">POS / New Sale</h1><p className="text-gray-500">Scan barcode or search medicine. FEFO batch is selected automatically.</p></div>
 <div className="card p-4"><input autoFocus className="input text-lg" placeholder="Scan barcode / search medicine..." value={q} onChange={e=>setQ(e.target.value)}/>{q&&<div className="mt-2 border rounded-xl overflow-hidden">{results.map(m=><button key={m.id} onClick={()=>add(m)} className="w-full text-left p-3 hover:bg-teal-50 border-b last:border-0"><b>{m.name}</b><span className="text-sm text-gray-500 ml-3">{m.barcode||m.productId}</span><span className="float-right">Rs. {m.batches[0]?.salePrice}</span></button>)}</div>}</div>
 <div className="card p-4 overflow-x-auto"><table className="table"><thead><tr><th>Medicine</th><th>Batch</th><th>Qty</th><th>Price</th><th>Total</th><th></th></tr></thead><tbody>{cart.map((x,i)=><tr key={x.batchId}><td>{x.name}<div className="text-xs text-gray-500">Exp {x.expiry}</div></td><td>{x.batch}</td><td><input className="input w-20" type="number" min="1" value={x.quantity} onChange={e=>update(i,Number(e.target.value))}/></td><td>{x.unitPrice}</td><td>{(x.quantity*x.unitPrice).toFixed(2)}</td><td><button className="text-red-600" onClick={()=>setCart(c=>c.filter((_,n)=>n!==i))}>Remove</button></td></tr>)}</tbody></table></div></div>
 <div className="card p-5 h-fit sticky top-4"><h2 className="font-black text-lg mb-5">Payment</h2><div className="space-y-3"><div className="flex justify-between"><span>Subtotal</span><b>Rs. {total.toFixed(2)}</b></div><div><label className="text-sm font-semibold">Payment method</label><select className="input mt-1" value={method} onChange={e=>setMethod(e.target.value)}>{["CASH","CARD","BANK","MOBILE_WALLET","CREDIT"].map(x=><option key={x}>{x}</option>)}</select></div><div><label className="text-sm font-semibold">Paid amount</label><input className="input mt-1" type="number" value={paid} onChange={e=>setPaid(e.target.value)} /></div><div className="border-t pt-4 flex justify-between text-xl"><span>Total</span><b>Rs. {total.toFixed(2)}</b></div><div className="flex justify-between"><span>Change</span><b>Rs. {change.toFixed(2)}</b></div><button onClick={complete} className="btn btn-primary w-full py-3">Complete Sale</button>{msg&&<div className="text-sm text-center text-teal-700">{msg}</div>}</div></div>
 </div>
}
